In [40]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
df = pd.read_csv('data/cancer_tumor_data_features.csv')

In [42]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [43]:
from sklearn.preprocessing import StandardScaler

In [44]:
scaler = StandardScaler()

In [45]:
scaled_X = scaler.fit_transform(df)

In [46]:
scaled_X

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [47]:
# Grab Covariance Matrix
covariance_matrix = np.cov(scaled_X, rowvar=False)

In [48]:
covariance_matrix[[29]]

array([[ 0.00707833,  0.11941522,  0.05110835,  0.00374418,  0.50019545,
         0.6885925 ,  0.51583646,  0.36931019,  0.43918535,  0.76864765,
         0.04964668, -0.04573495,  0.08558298,  0.01757017,  0.10165898,
         0.59201321,  0.44010274,  0.31120148,  0.07821694,  0.59236914,
         0.09365658,  0.2195082 ,  0.1392015 ,  0.07978726,  0.61871156,
         0.81188171,  0.68771957,  0.51201399,  0.53879512,  1.00176056]])

In [49]:
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [55]:
eigen_vectors[25]

array([ 2.10095880e-01,  1.43593173e-01, -2.36075625e-01, -9.13284153e-02,
       -1.21804107e-01,  4.77057929e-02, -1.40472938e-01, -8.40196588e-02,
       -1.00677822e-01, -1.72133632e-01, -1.97420469e-01, -3.71662503e-01,
        1.22793095e-02, -1.66470250e-01,  4.99560142e-02, -1.53734861e-01,
       -4.03712272e-03, -7.35745143e-02, -2.02007041e-02,  1.28415624e-02,
        3.56690394e-06, -4.86918180e-02, -7.05054136e-02,  1.00463424e-01,
        6.24384938e-01,  1.86749953e-01,  1.47920925e-01, -2.96764124e-02,
        2.29280589e-01, -1.81374867e-01])

In [51]:
eigen_values[29]

0.030025663090428513

In [26]:
num_components=2

In [27]:
# Get index sorting key based on Eigen Values
sorted_key = np.argsort(eigen_values)[::-1][:num_components]

In [28]:
sorted_key

array([0, 1], dtype=int64)

In [29]:
# Get num_components of Eigen Values and Eigen Vectors
eigen_values, eigen_vectors = eigen_values[sorted_key], eigen_vectors[:, sorted_key]

In [30]:
eigen_values

array([13.30499079,  5.7013746 ])

In [32]:
eigen_vectors[29]

array([0.13178394, 0.27533947])

In [33]:
# Dot product of original data and eigen_vectors are the principal component values
# This is the "projection" step of the original points on to the Principal Component
principal_components=np.dot(scaled_X,eigen_vectors)

In [36]:
scaled_X[568]

array([-1.80840125,  1.22179204, -1.81438851, -1.34778924, -3.11208479,
       -1.15075248, -1.11487284, -1.26181958, -0.8200699 , -0.56103238,
       -0.07027874,  0.3830925 , -0.15744905, -0.46615196,  0.04934236,
       -1.16351619, -1.05750068, -1.91344745,  0.75282996, -0.382754  ,
       -1.41089258,  0.76418957, -1.43273495, -1.07581292, -1.85901852,
       -1.2075525 , -1.30583065, -1.74506282, -0.04813821, -0.75120669])

In [37]:
principal_components

array([[ 9.19283683,  1.94858307],
       [ 2.3878018 , -3.76817174],
       [ 5.73389628, -1.0751738 ],
       ...,
       [ 1.25617928, -1.90229671],
       [10.37479406,  1.67201011],
       [-5.4752433 , -0.67063679]])

In [38]:
principal_components[568]

array([-5.4752433 , -0.67063679])